# Generated by Django 4.2.11 on 2024-04-10 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassEngraving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('description', models.CharField(max_length=1000, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CombatEngraving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('description', models.CharField(max_length=1000, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='Engraving',
        ),
        migrations.AlterField(
            model_name='allclass',
            name='first_class_engraving',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='first_eng', to='catalog.classengraving'),
        ),
        migrations.AlterField(
            model_name='allclass',
            name='second_class_engraving',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='second_eng', to='catalog.classengraving'),
        ),
    ]
