# Generated by Django 4.2.11 on 2024-04-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_classengraving_combatengraving_delete_engraving_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classengraving',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
