# Generated by Django 4.2.11 on 2024-04-11 06:35

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_classengraving_description'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='allclass',
            name='genre_name_case_insensitive_unique',
        ),
        migrations.AlterField(
            model_name='classengraving',
            name='description',
            field=models.TextField(default=2, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='combatengraving',
            name='description',
            field=models.TextField(max_length=1000, unique=True),
        ),
        migrations.AddConstraint(
            model_name='allclass',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='genre_name_case_insensitive_unique', violation_error_message='Class already exists (case insensitive match)'),
        ),
    ]
