# Generated by Django 4.2.11 on 2024-04-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_allclass_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allclass',
            name='icon',
            field=models.ImageField(default='E:\\LOA_AtropineEnjoyer\\AtropineEnjoyer\\catalog\\output_image.png', upload_to='icons'),
        ),
    ]
