# Generated by Django 4.2.11 on 2024-04-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_allclass_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allclass',
            name='icon',
            field=models.ImageField(default='media/default/default_icon.jpg', upload_to='icons'),
        ),
    ]
