# Generated by Django 4.2.11 on 2024-04-16 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_allclass_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Character name', max_length=40, unique=True)),
                ('the_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.allclass')),
            ],
        ),
    ]
