# Generated by Django 4.2.11 on 2024-04-16 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_character'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='the_class',
        ),
    ]
