# Generated by Django 4.2.11 on 2024-04-16 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_remove_character_the_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='the_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.allclass'),
        ),
    ]
