# Generated by Django 4.2.11 on 2024-04-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_character_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='ilv',
            field=models.IntegerField(default=0),
        ),
    ]
